# Generated by Django 4.0 on 2021-12-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todomodel',
            options={'ordering': ['-created_date']},
        ),
    ]
